name: reviewdog
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: read
  pull-requests: write
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3

      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review

      #- name: Run hadolint
      #  uses: reviewdog/action-hadolint@v1
      #  with:
      #    reporter: github-pr-review

      - name: Run alex
        uses: reviewdog/action-alex@v1
        with:
          reporter: github-pr-review

      - name: Run detect-secrets
        uses: reviewdog/action-detect-secrets@master
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review

      - name: Run dotenv-linter
        uses: dotenv-linter/action-dotenv-linter@v2
        with:
          reporter: github-pr-review
          dotenv_linter_flags: --skip UnorderedKey

      - name: Run rubocop
        id: rubocop
        uses: reviewdog/action-rubocop@v2
        continue-on-error: true
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-performance:gemfile rubocop-minitest:gemfile
          reporter: github-pr-review
          fail_on_error: true

      - name: Run reek
        id: reek
        uses: reviewdog/action-reek@v1
        continue-on-error: true
        with:
          reek_version: gemfile
          reporter: github-pr-review
          fail_on_error: true

      - name: Run rails_best_practices
        id: rails_best_practices
        uses: blooper05/action-rails_best_practices@v1
        continue-on-error: true
        with:
          rails_best_practices_version: gemfile
          reporter: github-pr-review
          fail_on_error: true

      - name: Check on failures
        if: steps.rubocop.outcome != 'success' || steps.reek.outcome != 'success' || steps.rails_best_practices.outcome != 'success'
        run: exit 1

  sast:
    name: sast
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3

      - name: Run brakeman
        id: brakeman
        uses: reviewdog/action-brakeman@v2
        with:
          brakeman_version: gemfile
          brakeman_flags: --run-all-checks
          reporter: github-pr-review
          fail_on_error: true

      - name: Run bundler-audit
        id: bundler_audit
        uses: andrewmcodes/bundler-audit-action@main
        env:
          GITHUB_TOKEN: ${{ github.token }}