name: Reviewdog (Lint & SAST)
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: read
  pull-requests: write
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    steps:
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Checkout code
        uses: actions/checkout@v3
      - run: |
          git fetch --no-tags --prune origin +refs/heads/*:refs/remotes/origin/*

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3

      - name: Run rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-performance:gemfile rubocop-minitest:gemfile
          reporter: github-pr-review